name: Automate deployment

on:
  workflow_call:
    outputs:
      NEW_PR:
        value: ${{ jobs.create_deployment.outputs.NEW_PR }}
        description: Resolves to true if a new deployment PR was created from the workflow run
    inputs:
      staging_branch:
        default: 'staging'
        required: false
        type: string
      main_branch:
        default: 'main'
        required: false
        type: string

jobs:
  create_deployment:
    name: Create deployment pr
    timeout-minutes: 5
    runs-on: ubuntu-latest
    outputs:
      NEW_PR: ${{ fromJSON(steps.deploy.outputs.result).NEW_PR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: firefliesai/.github
          path: firefliesai
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/scripts/auto_release.js

      - name: Add Trigger Token to env
        run: |
          $token = ${{ secrets.TRIGGER_TOKEN }} || ${{ secrets.GITHUB_TOKEN }}
          echo "TRIGGER_TOKEN=$token" >> $GITHUB_ENV

      - name: Create deployment PR
        id: deploy
        uses: actions/github-script@v6
        with:
          github-token: ${{ env.TRIGGER_TOKEN }}
          script: |
            const script = require('${{ github.workspace }}/firefliesai/.github/scripts/auto_release.js');

            const isNotMergeCommit = await script.checkMergeCommit({ github, context });
            if (isNotMergeCommit) return;

            context.payload.inputs = {
              main_branch: '${{ inputs.main_branch }}',
              staging_branch: '${{ inputs.staging_branch }}'
            }

            const newDeployment = await script.createDeploymentPR({ github, context });
            await script.generateSummaries({ github, context, core });

            return {
              NEW_PR: newDeployment
            }
