name: Build and Dispatch Event to GitOps Repository

on:
  workflow_call:
    inputs:
      tagPrefix:
        required: false
        type: string
        default: ""
      generateBasicTest:
        required: false
        type: boolean
        default: true
      dispatchDeploy:
        required: false
        type: boolean
        default: true
      cluster:
        required: false
        type: string
        default: ""
      context:
        required: false
        type: string
        default: "."
      imageName:
        required: false
        type: string
        default: ""
      directPush:
        required: false
        type: boolean
        default: false
      dockerFilePath:
        required: false
        type: string
        default: "Dockerfile"
      runner:
        required: false
        type: string
        default: ubuntu-latest
    outputs:
      IMAGE_TAG:
        description: Containerized image tag produced
        value: ${{ jobs.build_and_dispatch.outputs.IMAGE_TAG }}
      IMAGE_NAME_FULL_SHA:
        description: Containerized image tag produced
        value: ${{ jobs.build_and_dispatch.outputs.IMAGE_NAME_FULL_SHA }}
    secrets:
      pushToken:
        required: true
      dispatchToken:
        required: true
      buildArgs:
        required: false
        description: Build env var
      submodulesToken:
        required: false
        description: Token for fetching submodules when checkout

jobs:
  build_and_dispatch:
    outputs:
      IMAGE_TAG: ${{ steps.image-tag.outputs.IMAGE_NAME_WITH_SHA }}
    runs-on: ${{ inputs.runner }}
    steps:

    - name: Evaluating checkout condition
      id: checkout-config
      uses: actions/github-script@v6.4.0
      with:
        script: |
          if ('${{ secrets.submodulesToken }}' == '') {
            return {
              token: '${{ github.token }}',
              submodules: false,
            }
          }

          return {
            token: '${{ secrets.submodulesToken }}',
            submodules: 'recursive'
          }

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        token: ${{ fromJson(steps.checkout-config.outputs.result).token }}
        submodules: ${{ fromJson(steps.checkout-config.outputs.result).submodules }}
    
    - name: Extrapolate Environment Variables
      id: image-tag
      shell: bash
      env:
        PR_SHA: ${{ github.event.pull_request.head.sha }}
        CUSTOM_IMAGE_NAME: ${{ inputs.imageName }}
      run: |
        echo "Calculating BRANCH_NAME and IMAGE_NAME"
        IMG=$(echo ghcr.io/${{ github.repository }}/${{ github.event.repository.name }})
        if [[ $CUSTOM_IMAGE_NAME != '' ]]; then
          # If custom image name supplied, use it instead
          IMG=$(echo ghcr.io/${{ github.repository }}/$CUSTOM_IMAGE_NAME)
        fi
        TAG_SHA=${GITHUB_SHA}
        # if PR_SHA not null, use it instead.
        if [[ $PR_SHA != '' ]]; then
          TAG_SHA=$PR_SHA
        fi
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "IMAGE_NAME=$IMG" >> $GITHUB_ENV
        echo "IMAGE_NAME_WITH_SHA=$IMG:${{ inputs.tagPrefix }}${TAG_SHA::8}" >> $GITHUB_ENV
        echo "IMAGE_NAME_FULL_SHA=$IMG:${{ inputs.tagPrefix }}${TAG_SHA}" >> $GITHUB_ENV
        echo '::echo::on'
        # echo "::set-output name=IMAGE_NAME_WITH_SHA::$IMG:${{ inputs.tagPrefix }}${TAG_SHA::8}"
        echo "IMAGE_NAME_WITH_SHA=$IMG:${{ inputs.tagPrefix }}${TAG_SHA::8}" >> $GITHUB_OUTPUT
        # echo "::set-output name=IMAGE_NAME_FULL_SHA::$IMG:${{ inputs.tagPrefix }}${TAG_SHA}"
        echo "IMAGE_NAME_FULL_SHA=$IMG:${{ inputs.tagPrefix }}${TAG_SHA}" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.pushToken }}

    - name: Setup Docker context
      if: ${{ inputs.runner != 'ubuntu-latest' }}
      run: |
        docker context create builders

    - name: Setup Docker Buildkit
      uses: docker/setup-buildx-action@v2.2.1
      id: buildx
      with:
        install: true
        endpoint: ${{ inputs.runner == 'ubuntu-latest' && 'unix:///var/run/docker.sock' || 'builders' }}

    - name: Cache buildkit build
      uses: actions/cache@v3
      with:
        path: /tmp/cache
        key: ${{ env.IMAGE_NAME_WITH_SHA }}
        restore-keys: |
          ${{ env.IMAGE_NAME }}
    
    - name: Compute Metadata Labels
      id: metadata
      uses: docker/metadata-action@v4.3.0
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Build
      uses: docker/build-push-action@v3.3.0
      with:
        context: ${{ inputs.context }}
        load: ${{ !inputs.directPush }}
        push: ${{ inputs.directPush }}
        labels: ${{ steps.metadata.outputs.labels }}
        cache-from: type=local,src=/tmp/cache
        cache-to: type=local,mode=max,dest=/tmp/cache-new
        build-args: ${{ secrets.buildArgs }}
        file: ${{ inputs.dockerFilePath }}
        tags: |
          ${{ env.IMAGE_NAME_WITH_SHA }}
          ${{ env.IMAGE_NAME_FULL_SHA }}
          ${{ env.IMAGE_NAME}}:latest


    - name: Setup Container Structure Test
      if: inputs.directPush != true
      shell: bash
      run: |
        echo "Setup container structure test binary"
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - name: Generate Basic structure test
      if: inputs.generateBasicTest == true
      run: |
        echo "Generate basic container structure test"
        mkdir -p tests/structure
        cat <<EOF > tests/structure/basic.yaml
        schemaVersion: 2.0.0
        commandTests:
          - name: Node command available
            command: which
            args:
              - node
            expectedOutput:
              - /usr/local/bin/node
        EOF

    - name: Runs structure test
      if: inputs.directPush != true
      shell: bash
      run: |
        echo "Run test against ${IMAGE_NAME_WITH_SHA}"
        find ${{ inputs.context }}/tests/structure -name "*.yaml" -print0 | xargs -0 -I {} container-structure-test test --image ${IMAGE_NAME_WITH_SHA} --config {}

    - name: Push container image
      if: inputs.directPush != true
      run: |
        docker push $IMAGE_NAME_WITH_SHA
        docker push $IMAGE_NAME_FULL_SHA

    - name: Determine Cluster name
      uses: actions/github-script@v6
      id: cluster-name
      env:
        CLUSTER_NAME: ${{ inputs.cluster }}
        BRANCH_NAHE: ${{ env.BRANCH_NAME }}
      with:
        result-encoding: string
        script: |
          if (process.env.CLUSTER_NAME !== "") {
            return process.env.CLUSTER_NAME;
          }
          if (process.env.BRANCH_NAME !== 'master' && process.env.BRANCH_NAME !== 'main') {
            return 'staging';
          }
          // The origin most likely from master
          return 'production';

    - name: Dispatch Event to k8s-${{ steps.cluster-name.outputs.result }}
      uses: peter-evans/repository-dispatch@v2.1.1
      if: inputs.dispatchDeploy == true
      with:
        token: ${{ secrets.dispatchToken }}
        repository: firefliesai/k8s-${{ steps.cluster-name.outputs.result }}
        event-type: deployService
        client-payload: '{"repo": "${{ github.event.repository.name }}", "image": "${{ env.IMAGE_NAME_WITH_SHA }}", "branch": "${{ env.BRANCH_NAME }}" }'

    - name: Move cache # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#local-cache
      run: |
        rm -rf /tmp/cache
        mv /tmp/cache-new /tmp/cache
