on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: "Staging branch"

      main_branch:
        required: true
        type: string
        description: "Production branch"

      version:
        required: false
        type: string
        description: "Version to release"

      merge_back_from_main:
        required: false
        type: string
        description: "Merge back from main to develop"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release_workflow
        uses: hoangvvo/gitflow-workflow-action@0.3.2
        with:
          version: ${{ inputs.version }}
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          merge_back_from_main: ${{ inputs.merge_back_from_main }}
          slack: >
            {
              "channel": "feature-rollout",
              "username_mapping": {
                "hoangvvo": "U03B3E4UPV3",
                "dmkorb": "U0256NC37GT",
                "samuelayo": "UFHCU47B6",
                "sudotong": "U04KDQACM",
                "greguintow": "U02DDCN2UDC",
                "debloper": "USG05RE76",
                "jhho89": "U01HB1J09PF",
                "rogerpadilla": "U02FR157SG1",
                "grimmer0125": "U03BZH4CYBD",
                "dirathea": "U028RKKSNTW",
                "thadeuk": "U02G82H7QR2",
                "atomicman57": "U8EGXN80Z",
                "rgautam98": "U03AAU48XL3",
                "Riddhish97": "U04H6BQ6V0T",
                "azka-01": "U0258AV7R3M",
                "longyarnz": "UH8DQ3PRA",
                "ProKashif": "U01GUG3L4D6",
                "Lutif": "U01N11L5BD0",
                "FatimahAbdullah": "U0277DZ97JL",
                "Nilomiranda": "U02GNJGBPJ7",
                "ugokoli": "U01378G4H28",
                "MrMuhammadAbdullah1704": "U01G1J5HYG5",
                "sumitkolhe": "U04PZD94TAR",
                "carloscdante": "U04FY3MGBV4",
                "wilforlan": "UC0UWLSQ2",
                "anooppoommen": "U038VBD2XCP",
                "hamidladan": "U043NHY5HNF",
                "zypher606": "U021VD0J2UE",
                "samuelfruhauf": "U02M3F53PU7",
                "MBilal07": "U022EQJQBMF",
                "shivamluthra": "U043X0VCASE",
                "haziqAhmed92": "U02HAU99A1G",
                "htkimura": "U061P10ADNV"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Prefill release summary
        if: ${{ steps.release_workflow.outputs.type == 'release' && steps.release_workflow.outputs.pull_number && steps.release_workflow.outputs.pull_numbers_in_release }}
        uses: actions/github-script@v7
        with:
          script: |
            const pull_number = ${{ steps.release_workflow.outputs.pull_number }};
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number,
            });

            const mergedPrNumbers = "${{ steps.release_workflow.outputs.pull_numbers_in_release }}".split(',').map(Number);
            const body = context.payload.pull_request.body;

            // Get the PRs and parse the release summary
            const mergedPrs = await Promise.all(mergedPrNumbers.map(async (prNumber) => {
              const pr = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
              const regex = /## What does this PR do\?\n\n(.*?)\n\n##/s;
              if (!pr.data.body) {
                return;
              }
              const regex = /\#\# What does this PR do\?([\s\S]*?)\n\#\#/gm;
              const match = regex.exec(pr.data.body)
              return match?.[1]?.trim();
            })).then((prs) => prs.filter(Boolean));
            const releaseSummary = mergedPrs.join('\n');

            // Update the PR body
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number,
              body: body.replace("## Release summary", `## Release summary\n\n${releaseSummary}`)
            });
