on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: "Staging branch"

      main_branch:
        required: true
        type: string
        description: "Production branch"

      version:
        required: true
        type: string
        description: "Version to release"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: hoangvvo/gitflow-workflow-action@0.2.4
        with:
          version: ${{ inputs.version }}
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
