on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: "Staging branch"

      main_branch:
        required: true
        type: string
        description: "Production branch"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: hoangvvo/gitflow-workflow-action@0.2.4
        with:
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          slack: >
            {
              "channel": "feature-rollout",
              "username_mapping": {
                "hoangvvo": "U03B3E4UPV3",
                "dmkorb": "U0256NC37GT",
                "samuelayo": "UFHCU47B6",
                "sudotong": "U04KDQACM",
                "greguintow": "U02DDCN2UDC",
                "debloper": "USG05RE76",
                "jhho89": "U01HB1J09PF",
                "rogerpadilla": "U02FR157SG1",
                "grimmer0125": "U03BZH4CYBD",
                "dirathea": "U028RKKSNTW",
                "thadeuk": "U02G82H7QR2",
                "BrTkCa": "U02HA9NC2UT",
                "atomicman57": "U8EGXN80Z",
                "rgautam98": "U03AAU48XL3",
                "Riddhish97": "U04H6BQ6V0T"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
