on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: 'Staging branch'

      main_branch:
        required: true
        type: string
        description: 'Production branch'

      version:
        required: false
        type: string
        description: 'Version to release'

      merge_back_from_main:
        required: false
        type: string
        description: 'Merge back from production branch instead of release branch to staging branch'

      package_json_update_version:
        required: false
        default: false
        type: boolean
        description: 'Set to true to update package.json version to the release version'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release_workflow_dry_run
        if: github.event_name == 'workflow_dispatch'
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          dry_run: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.FIREFLIES_BOT_TOKEN }}

      - id: generate_pr_summary
        name: generate PR summary
        if: ${{ steps.release_workflow_dry_run.outputs.type == 'release' && steps.release_workflow_dry_run.outputs.pull_numbers_in_release }}
        uses: actions/github-script@v7
        with:
          script: |
            const pull_numbers_in_release = '${{ steps.release_workflow_dry_run.outputs.pull_numbers_in_release }}';
            const latest_release_tag_name = '${{ steps.release_workflow_dry_run.outputs.latest_release_tag_name }}';

            try {
              const mergedPrNumbers = Array.from(new Set(pull_numbers_in_release.split(',').map(Number)));
              
              // Get the PRs and parse the release summary
              const mergedPrs = await Promise.all(mergedPrNumbers.map(async (prNumber) => {
                const pr = await github.rest.pulls.get({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber
                });
                const body = pr.data.body || "";
                const regex = /\#\# What does this PR do\?([\s\S]*?)\n\#\#/gm;
                let match = regex.exec(body)?.[1]?.trim();
                
                // try to remove empty lines and format bullets
                match = match?.split('\n').map(s => s.trim()).filter(Boolean).map(
                  s => s.startsWith('-') || s.startsWith('*') ? s : `* ${s}`
                ).join('\n');

                let type = 0 // patch
                if (body.includes("[x] Feature")) {
                  type = 1 // minor
                }

                return {
                  title: pr.data.title,
                  summary: match,
                  type,
                }
              })).then((prs) => prs.filter(pr => !!pr));
              
              const releaseSummary = mergedPrs.map((pr) => {
                return `${pr.title}\n${pr.summary}`;
              }).join('\n\n');

              // Truncate the release summary if it's too long
              const maxLength = 65000; // Leaving some buffer, as max is 65536
              if (releaseSummary.length > maxLength) {
                releaseSummary = releaseSummary.substring(0, maxLength) + "\n\n... (truncated due to length)";
              }

              const versionIncrementType = Math.max(...mergedPrs.map((pr) => pr.type));
              const versionIncrement = ['patch', 'minor', 'major'][versionIncrementType] || 'patch';

              console.log(`Determined suggested version increment (${versionIncrement})`)
              console.log(`Release summary:\n${releaseSummary}`);

              core.setOutput('release_summary', releaseSummary);
              core.setOutput('version_increment', versionIncrement);
            } catch (error) {
              console.log(`Could not determine release summary and version_increment`)
              console.log(error)
            }

      - id: release_workflow
        uses: hoangvvo/gitflow-workflow-action@0.3.7
        with:
          version: ${{ inputs.version }}
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          merge_back_from_main: ${{ inputs.merge_back_from_main }}
          release_summary: ${{ steps.generate_pr_summary.outputs.release_summary }}
          version_increment: ${{ steps.generate_pr_summary.outputs.version_increment }}
          slack: >
            {
              "channel": "feature-rollout",
              "username_mapping": {
                "hoangvvo": "U03B3E4UPV3",
                "dmkorb": "U0256NC37GT",
                "samuelayo": "UFHCU47B6",
                "sudotong": "U04KDQACM",
                "greguintow": "U02DDCN2UDC",
                "debloper": "USG05RE76",
                "jhho89": "U01HB1J09PF",
                "rogerpadilla": "U02FR157SG1",
                "grimmer0125": "U03BZH4CYBD",
                "dirathea": "U028RKKSNTW",
                "thadeuk": "U02G82H7QR2",
                "atomicman57": "U8EGXN80Z",
                "rgautam98": "U03AAU48XL3",
                "Riddhish97": "U04H6BQ6V0T",
                "azka-01": "U0258AV7R3M",
                "longyarnz": "UH8DQ3PRA",
                "ProKashif": "U01GUG3L4D6",
                "Lutif": "U01N11L5BD0",
                "FatimahAbdullah": "U0277DZ97JL",
                "Nilomiranda": "U02GNJGBPJ7",
                "ugokoli": "U01378G4H28",
                "MrMuhammadAbdullah1704": "U01G1J5HYG5",
                "sumitkolhe": "U04PZD94TAR",
                "carloscdante": "U04FY3MGBV4",
                "wilforlan": "UC0UWLSQ2",
                "anooppoommen": "U038VBD2XCP",
                "hamidladan": "U043NHY5HNF",
                "zypher606": "U021VD0J2UE",
                "samuelfruhauf": "U02M3F53PU7",
                "MBilal07": "U022EQJQBMF",
                "shivamluthra": "U043X0VCASE",
                "haziqAhmed92": "U02HAU99A1G",
                "htkimura": "U061P10ADNV",
                "xage93": "U043X1K6810",
                "kashyap-sojitra": "U05RBAXUJUX",
                "ghimire007": "U065MEQ96AU",
                "fisfat": "UKLEEP4F6",
                "gabrielcsf": "U06180NQGPQ",
                "Serdar-FF": "U067AUL8HG8",
                "cchitsiang": "U0544MQ3ZNK",
                "cokpakpo": "U016WC4SFK6",
                "darangi": "U03D9GMQM7T",
                "deepak29ff": "U05R3RBKQ0G",
                "jonathantissot": "U04UV9H5J23",
                "karchig": "U01JKURD05U",
                "willpoint": "UJ7P83H7T",
                "zekeri-riya": "U01374NRKGU",
                "sleemkeen": "U01QSFC4QUE",
                "rafakato": "U02PMSZDNE6",
                "sahilchauhan36": "U068VP8DLEL",
                "mHamza301": "U022K5F8ZB3",
                "m3rryqold": "U0560E5H41F",
                "mustay": "U05M9EJMY72",
                "marinamsm": "U02GY8JRYLA",
                "alirazachishti": "U01FPUCJDP1",
                "ndeitch": "U024CECHHBP",
                "robert-sarosi": "U06MR0J3MC0",
                "FoysalOsmany": "U01UDGB0RR8",
                "codinger41": "U06S3KV9G5P",
                "anveshr1": "U01PC2FDE65",
                "noghartt": "U074XBKUX1R",
                "luckpng": "U0785C4MZ1A",
                "Nickrosendo": "U076TTEDQJX",
                "asozcan": "U07FEPGH677"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.FIREFLIES_BOT_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - uses: actions/checkout@v4 #check out to the release branch to bump package json version
        if: ${{ steps.release_workflow.outputs.release_branch && inputs.package_json_update_version }}
        with:
          ref: ${{ steps.release_workflow.outputs.release_branch }}

      - name: Update package.json version
        if: ${{ steps.release_workflow.outputs.release_branch && inputs.package_json_update_version }}
        run: |
          npm version ${{ steps.release_workflow.outputs.version }}
          git commit -a -m "version: ${{ steps.release_workflow.outputs.version }}"
          git push origin ${{ steps.release_workflow.outputs.release_branch }}
