on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: "Staging branch"

      main_branch:
        required: true
        type: string
        description: "Production branch"

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: hoangvvo/gitflow-workflow-action@0.2.4
        with:
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          slack: >
            {
              "channel": "feature-rollout",
              "username_mapping": {
                "hoangvvo": "U03B3E4UPV3",
                "dmkorb": "U0256NC37GT",
                "samuelayo": "UFHCU47B6",
                "sudotong": "U04KDQACM",
                "greguintow": "U02DDCN2UDC",
                "debloper": "USG05RE76",
                "jhho89": "U01HB1J09PF",
                "rogerpadilla": "U02FR157SG1",
                "grimmer0125": "U03BZH4CYBD",
                "dirathea": "U028RKKSNTW",
                "thadeuk": "U02G82H7QR2",
                "atomicman57": "U8EGXN80Z",
                "rgautam98": "U03AAU48XL3",
                "Riddhish97": "U04H6BQ6V0T",
                "azka-01": "U0258AV7R3M",
                "longyarnz": "UH8DQ3PRA",
                "ProKashif": "U01GUG3L4D6",
                "Lutif": "U01N11L5BD0",
                "FatimahAbdullah": "U0277DZ97JL",
                "Nilomiranda": "U02GNJGBPJ7",
                "ugokoli": "U01378G4H28",
                "MrMuhammadAbdullah1704": "U01G1J5HYG5",
                "sumitkolhe": "D04TLKW7A0J",
                "carloscdante": "D04HD1C8PMW",
                "wilforlan": "UC0UWLSQ2",
                "anooppoommen": "U038VBD2XCP",
                "hamidladan": "U043NHY5HNF",
                "zypher606": "U021VD0J2UE"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
