# DEPRECATED - USE gitflow-release instead

on:
  workflow_call:
    inputs:
      develop_branch:
        required: true
        type: string
        description: 'Staging branch'

      main_branch:
        required: true
        type: string
        description: 'Production branch'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: hoangvvo/gitflow-workflow-action@0.3.3
        with:
          develop_branch: ${{ inputs.develop_branch }}
          main_branch: ${{ inputs.main_branch }}
          slack: >
            {
              "channel": "feature-rollout",
              "username_mapping": {
                "hoangvvo": "U03B3E4UPV3",
                "dmkorb": "U0256NC37GT",
                "samuelayo": "UFHCU47B6",
                "sudotong": "U04KDQACM",
                "greguintow": "U02DDCN2UDC",
                "jhho89": "U01HB1J09PF",
                "grimmer0125": "U03BZH4CYBD",
                "thadeuk": "U02G82H7QR2",
                "atomicman57": "U8EGXN80Z",
                "rgautam98": "U03AAU48XL3",
                "Riddhish97": "U04H6BQ6V0T",
                "azka-01": "U0258AV7R3M",
                "longyarnz": "UH8DQ3PRA",
                "ProKashif": "U01GUG3L4D6",
                "Lutif": "U01N11L5BD0",
                "FatimahAbdullah": "U0277DZ97JL",
                "Nilomiranda": "U02GNJGBPJ7",
                "ugokoli": "U01378G4H28",
                "MrMuhammadAbdullah1704": "U01G1J5HYG5",
                "sumitkolhe": "U04PZD94TAR",
                "carloscdante": "U04FY3MGBV4",
                "wilforlan": "UC0UWLSQ2",
                "zypher606": "U021VD0J2UE",
                "samuelfruhauf": "U02M3F53PU7",
                "MBilal07": "U022EQJQBMF",
                "haziqAhmed92": "U02HAU99A1G",
                "htkimura": "U061P10ADNV",
                "xage93": "U043X1K6810",
                "ghimire007": "U065MEQ96AU",
                "fisfat": "UKLEEP4F6",
                "Serdar-FF": "U067AUL8HG8",
                "cchitsiang": "U0544MQ3ZNK",
                "cokpakpo": "U016WC4SFK6",
                "darangi": "U03D9GMQM7T",
                "deepak29ff": "U05R3RBKQ0G",
                "jonathantissot": "U04UV9H5J23",
                "karchig": "U01JKURD05U",
                "willpoint": "UJ7P83H7T",
                "zekeri-riya": "U01374NRKGU",
                "sleemkeen": "U01QSFC4QUE",
                "rafakato": "U02PMSZDNE6",
                "mHamza301": "U022K5F8ZB3",
                "m3rryqold": "U0560E5H41F",
                "mustay": "U05M9EJMY72",
                "marinamsm": "U02GY8JRYLA",
                "alirazachishti": "U01FPUCJDP1",
                "ndeitch": "U024CECHHBP",
                "robert-sarosi": "U06MR0J3MC0",
                "FoysalOsmany": "U01UDGB0RR8",
                "noghartt": "U074XBKUX1R",
                "luckpng": "U0785C4MZ1A",
                "Nickrosendo": "U076TTEDQJX",
                "asozcan": "U07FEPGH677",
                "airas-fireflies": "U07K5NA0J1K",
                "Eckzzo": "U07SHTKLKUJ",
                "caiocampoos": "U07S6AXF9T9",
                "guilherme-vp": "U0812PGPGE6"
              }
            }
        env:
          GITHUB_TOKEN: ${{ secrets.FIREFLIES_BOT_TOKEN }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
