name: Run Structure Test

on:
  workflow_call:
    inputs:
      generateBasicTest:
        required: false
        type: boolean
        default: true
      context:
        required: false
        type: string
        default: "."
    secrets:
      buildArgs:
        required: false
        description: Build env var
      submodulesToken:
        required: false
        description: Token for fetching submodules when checkout

jobs:
  structure-test:
    runs-on: k8s-runner
    steps:

    - name: Evaluating checkout condition
      id: checkout-config
      uses: actions/github-script@v6.4.0
      with:
        script: |
          if ('${{ secrets.submodulesToken }}' == '') {
            return {
              token: '${{ github.token }}',
              submodules: false,
            }
          }

          return {
            token: '${{ secrets.submodulesToken }}',
            submodules: 'recursive'
          }

    - name: Checkout source
      uses: actions/checkout@v3
      with:
        token: ${{ fromJson(steps.checkout-config.outputs.result).token }}
        submodules: ${{ fromJson(steps.checkout-config.outputs.result).submodules }}

    - name: Extrapolate Environment Variables
      shell: bash
      run: |
        echo "Calculating BRANCH_NAME and IMAGE_NAME"
        IMG=$(echo ghcr.io/${{ github.repository }}/${{ github.event.repository.name }})
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "IMAGE_NAME=$IMG" >> $GITHUB_ENV
        echo "IMAGE_NAME_WITH_SHA=$IMG:${GITHUB_SHA::8}" >> $GITHUB_ENV

    - name: Setup Docker Buildkit
      uses: docker/setup-buildx-action@v2.2.1
      id: buildx
      with:
        install: true
        endpoint: default

    - name: Cache buildkit build
      uses: actions/cache@v3
      with:
        path: /tmp/cache
        key: ${{ env.IMAGE_NAME_WITH_SHA }}
        restore-keys: |
          ${{ env.IMAGE_NAME }}

    - name: Build
      uses: docker/build-push-action@v3.3.0
      with:
        context: ${{ inputs.context }}
        load: true
        cache-from: type=local,src=/tmp/cache
        build-args: ${{ secrets.buildArgs }}
        tags: |
          ${{ env.IMAGE_NAME_WITH_SHA }}
          ${{ env.IMAGE_NAME}}:latest

    - name: Setup Container Structure Test
      shell: bash
      run: |
        echo "Setup container structure test binary"
        curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
        chmod +x container-structure-test-linux-amd64
        sudo mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test

    - name: Generate Basic structure test
      if: inputs.generateBasicTest == true
      run: |
        echo "Generate basic container structure test"
        mkdir -p tests/structure
        cat <<EOF > tests/structure/basic.yaml
        schemaVersion: 2.0.0
        commandTests:
          - name: Node command available
            command: which
            args:
              - node
            expectedOutput:
              - /usr/local/bin/node
        EOF

    - name: Runs structure test
      shell: bash
      run: |
        echo "Run test against ${IMAGE_NAME_WITH_SHA}"
        find ${{ inputs.context }}/tests/structure -name "*.yaml" -print0 | xargs -0 -I {} container-structure-test test --image ${IMAGE_NAME_WITH_SHA} --config {}
