name: Token Checker

on:
  pull_request:

jobs:

  check-token:
    strategy:
      fail-fast: false
      matrix:
        token:
          - ${{ secrets.ACCESS_TOKEN }}
          - ${{ secrets.CROSS_REPO_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Verify user
        run: |
          cat $GITHUB_TOKEN | gh auth login --with-token
        env:
          GITHUB_TOKEN: ${{ matrix.token }}